services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:example@mongo:27017/kitchen?authSource=admin
    depends_on:
      - mongo

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      EXPO_HOST: tunnel
    depends_on:
      - backend

  frontend-test:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    profiles:
      - test
    environment:
      CI: "true"
      NODE_ENV: test
    command: npm run test

  frontend-coverage:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    profiles:
      - test
    environment:
      CI: "true"
      NODE_ENV: test
    command: npm run test:coverage

volumes:
  mongo_data:
