import { fireEvent, screen, waitFor } from '@testing-library/react-native';
import PlannerScreen from './PlannerScreen';
import { renderWithProviders } from '../../test/render';

const mockPush = jest.fn();
const mockReplace = jest.fn();

jest.mock('expo-router', () => ({
  useRouter: () => ({
    push: mockPush,
    replace: mockReplace,
  }),
}));

jest.mock('../../lib/services', () => ({
  kitchenService: {
    syncFromPlan: jest.fn(),
  },
  plannerService: {
    getCurrentPlan: jest.fn(),
  },
}));

const { kitchenService, plannerService } = jest.requireMock('../../lib/services') as {
  kitchenService: { syncFromPlan: jest.Mock };
  plannerService: { getCurrentPlan: jest.Mock };
};

describe('PlannerScreen navigation', () => {
  beforeEach(() => {
    mockPush.mockClear();
    mockReplace.mockClear();
    kitchenService.syncFromPlan.mockResolvedValue({});
    plannerService.getCurrentPlan.mockResolvedValue({
      id: 'plan-1',
      title: 'Weekly Meal Planner',
      subtitle: 'Autogenerated from goals, allergies, time limits, and planning mode',
      target: {
        calories: '2,100 kcal',
        macros: 'P150 C180 F70',
      },
      badge: 'High protein',
      days: [
        {
          dayKey: 'mon',
          label: 'Monday',
          meals: [
            {
              slot: 'breakfast',
              recipeId: 'recipe-1',
              title: 'Oats',
              shortLabel: 'Oats',
              calories: 400,
              tags: [],
            },
          ],
        },
      ],
    });
  });

  it('uses push for planner chat and replace for Kitchen main-screen navigation', async () => {
    renderWithProviders(<PlannerScreen />);

    await waitFor(() => {
      expect(screen.getByText('Modify / Generate Plan')).toBeTruthy();
    });

    fireEvent.press(screen.getByText('Modify / Generate Plan'));
    fireEvent.press(screen.getByText('Build Grocery List'));

    await waitFor(() => {
      expect(kitchenService.syncFromPlan).toHaveBeenCalled();
    });

    expect(mockPush).toHaveBeenCalledWith('/planner/chat');
    expect(mockReplace).toHaveBeenCalledWith('/kitchen/to-buy');
  });
});
