import { useEffect, useState } from 'react';
import { useRouter } from 'expo-router';
import { Paragraph, Text, XStack, YStack } from 'tamagui';
import AppScaffold from '../../components/layout/AppScaffold';
import {
  ActionButton,
  PillBadge,
  SectionCard,
  SectionHeading,
  StickyFooter,
  palette,
} from '../../components/ui/primitives';
import { kitchenService, plannerService } from '../../lib/services';
import { useUiStore } from '../../lib/store/uiStore';
import type { WeeklyPlanResponse } from '../../lib/types/contracts';

function Divider() {
  return <YStack height={1} backgroundColor={palette.border} />;
}

export default function PlannerScreen() {
  const router = useRouter();
  const pushToast = useUiStore((state) => state.pushToast);
  const [plan, setPlan] = useState<WeeklyPlanResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const load = async () => {
      try {
        setPlan(await plannerService.getCurrentPlan());
      } catch (caughtError) {
        setError(caughtError instanceof Error ? caughtError.message : 'Unable to load planner.');
      } finally {
        setLoading(false);
      }
    };

    void load();
  }, []);

  return (
    <AppScaffold
      title="Weekly Meal Planner"
      subtitle="Autogenerated from goals, allergies, time limits, and planning mode"
      activeTab="planner"
      footer={
        plan ? (
          <StickyFooter>
            <ActionButton variant="secondary" onPress={() => router.push('/planner/chat')}>
              Modify / Generate Plan
            </ActionButton>
            <ActionButton
              onPress={async () => {
                await kitchenService.syncFromPlan();
                pushToast({
                  title: 'Grocery list ready',
                  description: 'Kitchen To Buy was refreshed from your current plan.',
                  tone: 'success',
                });
                router.replace('/kitchen/to-buy');
              }}
            >
              Build Grocery List
            </ActionButton>
          </StickyFooter>
        ) : undefined
      }
    >
      {loading ? (
        <SectionCard>
          <Text color={palette.text} fontSize={14} fontWeight="700">
            Loading plan...
          </Text>
        </SectionCard>
      ) : error ? (
        <SectionCard tone="danger">
          <Text color={palette.danger} fontSize={14} fontWeight="700">
            {error}
          </Text>
        </SectionCard>
      ) : plan ? (
        <>
          <SectionCard>
            <SectionHeading title="Week Target" />
            <XStack gap={12}>
              <YStack flex={1} gap={2}>
                <Text color={palette.textStrong} fontSize={28} fontWeight="700">
                  {plan.target.calories}
                </Text>
                <Paragraph color={palette.textSecondary} fontSize={12}>
                  Daily calories
                </Paragraph>
              </YStack>
              <YStack flex={1} gap={2}>
                <Text color={palette.primary} fontSize={18} fontWeight="700">
                  {plan.target.macros}
                </Text>
                <Paragraph color={palette.textSecondary} fontSize={12}>
                  Protein / Carbs / Fat
                </Paragraph>
              </YStack>
            </XStack>
          </SectionCard>

          <SectionCard>
            <SectionHeading
              title="Generated Week"
              subtitle="Current accepted version of the week."
              accessory={<PillBadge label={plan.badge} tone="accent" />}
            />
            <YStack gap={0}>
              {plan.days.map((day, index) => (
                <YStack key={day.dayKey}>
                  {index > 0 ? <Divider /> : null}
                  <YStack paddingVertical={12} gap={4}>
                    <Text color={palette.text} fontSize={13} fontWeight="700">
                      {day.label}
                    </Text>
                    <Paragraph color={palette.textSecondary} fontSize={13} lineHeight={18}>
                      {day.meals.map((meal) => meal.shortLabel).join(' • ')}
                    </Paragraph>
                  </YStack>
                </YStack>
              ))}
            </YStack>
          </SectionCard>
        </>
      ) : null}
    </AppScaffold>
  );
}
