import { getCurrentPlanTarget, getMockDataSnapshot, useMockAppStore } from '../mock/mockStore';
import { requireAppUserId, withDelay } from './utils';
import type {
  CreatePlannerRevisionPayload,
  GroceryPreviewResponse,
  WeeklyPlanResponse,
  WeeklyPlanRevisionResponse,
} from '../types/contracts';

function toWeeklyPlanResponse(userId: string): WeeklyPlanResponse {
  const snapshot = getMockDataSnapshot();
  const currentPlanId = snapshot.currentWeeklyPlanByUserId[userId];
  const plan = snapshot.weeklyPlans[currentPlanId];
  const acceptedRevision =
    snapshot.weeklyPlanRevisionsByPlanId[plan.id]?.find((revision) => revision.id === plan.acceptedRevisionId) ??
    snapshot.weeklyPlanRevisionsByPlanId[plan.id]?.[0];

  return {
    id: plan.id,
    title: 'Weekly Meal Planner',
    subtitle: 'Autogenerated from goals, allergies, time limits, and planning mode',
    target: getCurrentPlanTarget(plan),
    badge: acceptedRevision?.latestOutput.badge ?? 'batch-cooking',
    days: plan.days,
  };
}

async function getCurrentPlan(): Promise<WeeklyPlanResponse> {
  const userId = requireAppUserId();
  return withDelay(toWeeklyPlanResponse(userId));
}

async function getGroceryPreview(): Promise<GroceryPreviewResponse> {
  const userId = requireAppUserId();
  const snapshot = getMockDataSnapshot();
  const groceryList = snapshot.groceryLists[snapshot.currentGroceryListByUserId[userId]];
  if (!groceryList) {
    throw new Error('No grocery list found.');
  }

  return withDelay({
    weeklyPlanId: groceryList.weeklyPlanId,
    items: groceryList.items.map((item) => ({
      itemId: item.itemId,
      name: item.name,
      quantity: `${item.quantity.value} ${item.quantity.unit}`,
      note: item.notes ?? 'Needed this week',
    })),
  });
}

async function getRevisions(): Promise<WeeklyPlanRevisionResponse[]> {
  const userId = requireAppUserId();
  const snapshot = getMockDataSnapshot();
  const planId = snapshot.currentWeeklyPlanByUserId[userId];
  const revisions = (snapshot.weeklyPlanRevisionsByPlanId[planId] ?? [])
    .slice()
    .sort((left, right) => right.revisionNumber - left.revisionNumber);

  return withDelay(
    revisions.map((revision) => ({
      id: revision.id,
      revisionNumber: revision.revisionNumber,
      chat: revision.chat,
      latestOutput: revision.latestOutput,
    })),
  );
}

async function getLatestRevision(): Promise<WeeklyPlanRevisionResponse> {
  const revisions = await getRevisions();
  if (!revisions[0]) {
    throw new Error('No planner revisions found.');
  }
  return revisions[0];
}

async function createRevision(payload: CreatePlannerRevisionPayload): Promise<WeeklyPlanRevisionResponse> {
  const userId = requireAppUserId();
  const revision = useMockAppStore.getState().createPlannerRevision(userId, payload.userMessage);

  return withDelay({
    id: revision.id,
    revisionNumber: revision.revisionNumber,
    chat: revision.chat,
    latestOutput: revision.latestOutput,
  });
}

async function acceptRevision(revisionId: string): Promise<WeeklyPlanResponse> {
  const userId = requireAppUserId();
  useMockAppStore.getState().acceptPlannerRevision(userId, revisionId);
  return withDelay(toWeeklyPlanResponse(userId));
}

async function generateCurrent(): Promise<WeeklyPlanResponse> {
  return getCurrentPlan();
}

export const plannerService = {
  acceptRevision,
  createRevision,
  generateCurrent,
  getCurrentPlan,
  getGroceryPreview,
  getLatestRevision,
  getRevisions,
};

export default plannerService;
